### ISSUE TITLE
Github便捷化插件

### ISSUE THREAD

**Issue by bitmori** [neonmori/neonmori.github.io#11]
https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-code-colors

**Comment by bitmori** [comment]
https://github.com/mdo/github-wide

**Comment by bitmori** [comment]
https://github.com/StylishThemes/GitHub-Dark

**Comment by bitmori** [comment]
https://github.com/sindresorhus/refined-github

```css
.rgh-monospace-textareas #merge_title_field,
.rgh-monospace-textareas #commit-summary-input,
.rgh-monospace-textareas textarea {
	font-family: Sarasa-Mono-T-J-Light, SFMono-Regular, Consolas, 'Liberation Mono', Menlo, Courier, monospace !important;
}
```
